### ISSUE TITLE
Exclude components for systems

### ISSUE THREAD

**Issue by matkve** [Avokadoen/ecez#114]
With queries it is possible to specify components that should not be included in the matching entities. This is very useful, and it would be nice to be able to do this for systems as well.

**Comment by Avokadoen** [comment]
Blocked by #108

**Comment by Avokadoen** [comment]
No longer blocked as of [17074c2](https://github.com/Avokadoen/ecez/commit/17074c24a677e2f8ef83cf5f8e4f02d527688978)

**Comment by Avokadoen** [comment]
Should be included as an argument when calling triggerEvent
